apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::921483785411:role/default-eks-node-group-202509260943290070000000001
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::921483785411:user/jenkins-ecr
      username: jenkins-ecr
      groups:
        - system:masters
