apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-flashscale
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "flashscale-backend"
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ["flashscale"]
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: flashscale-backend
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: "8000"

      - job_name: "node-exporter"
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: ["monitoring"]
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: prometheus-prometheus-node-exporter

      - job_name: "kube-state-metrics"
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - monitoring
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: prometheus-kube-state-metrics;8080
        # Fallback static target
        static_configs:
          - targets:
            - "prometheus-kube-state-metrics.monitoring.svc.cluster.local:8080"

      - job_name: "cadvisor"
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        metrics_path: /metrics/cadvisor

      - job_name: "kubelet"
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        metrics_path: /metrics/resource
