apiVersion: apps/v1
kind: Deployment
metadata:
  name: flashscale-backend-blue
  namespace: flashscale
  labels:
    app: flashscale-backend
    color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flashscale-backend
      color: blue
  template:
    metadata:
      labels:
        app: flashscale-backend
        color: blue
    spec:
      containers:
        - name: backend
          image: 921483785411.dkr.ecr.us-east-1.amazonaws.com/flashscale-backend:latest
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
          resources:       # ✅ correctly indented
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
