apiVersion: apps/v1
kind: Deployment
metadata:
  name: flashscale-frontend-blue
  namespace: flashscale
  labels:
    app: flashscale-frontend
    color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flashscale-frontend
      color: blue
  template:
    metadata:
      labels:
        app: flashscale-frontend
        color: blue
    spec:
      containers:
        - name: frontend
          image: 921483785411.dkr.ecr.us-east-1.amazonaws.com/flashscale-frontend:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
